version: "3.9"

services:
  node-crud:
    image: crud
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - node-frontend-crud
      - node-backend-crud
    volumes:
      - appdata:/var/www/html
    restart: always
    environment:
      - DATABASE_URL=mongodb://mongo:27017/crud
      - MONGODB_URL=mongodb://mongo:27017/crud
      - MONGO_DEFAULT_DATABASE=crud
      - API_URL=http://localhost:3000

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - node-backend-crud
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_ENABLE_ADMIN: true
      ME_CONFIG_SITE_ENABLE_DEBUGGER: true
      MONGODB_URL:mongodb: http//mongo:27017/crud
      ME_CONFIG_SITE_ENABLE_TRIGGERS: true

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_SSL_ENABLED: true
      ME_CONFIG_SITE_SSL_CRT_PATH: /etc/ssl/certs/nodecrud.crt
      ME_CONFIG_SITE_SSL_KEY_PATH: /etc/ssl/private/nodecrud.key
    volumes:
      - ./ssl/nodecrud.crt:/etc/ssl/certs/nodecrud.crt
      - ./ssl/nodecrud.key:/etc/ssl/private/nodecrud.key
    networks:
      - node-frontend-crud
      - node-backend-crud
    restart: always

  proxy:
    container_name: proxy
    image: nginx
    depends_on:
      - node-crud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/nodecrud.crt:/etc/ssl/certs/nodecrud.crt
      - ./ssl/nodecrud.key:/etc/ssl/private/nodecrud.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - node-frontend-crud
    restart: always

volumes:
  mongodata:
  appdata:

networks:
  node-frontend-crud:
  node-backend-crud:
    internal: true