version: "3.9"

services:
  todoapp:
    image: todoapp
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - node-frontend-todoapp
      - node-backend-todoapp
    volumes:
      - appdata:/var/www/html
    restart: always
    environment:
      - DATABASE_URL=mongodb://mongo:27017/todoapp
      - DB_URL=mongodb://mongo:27017/todoapp
      - MONGODB_URL=mongodb://mongo:27017/todoapp
      - MONGO_DEFAULT_DATABASE=todoapp
      - API_URL=http://localhost:3000

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - node-backend-todoapp
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_ENABLE_ADMIN: true
      ME_CONFIG_SITE_ENABLE_DEBUGGER: true
      ME_CONFIG_SITE_ENABLE_TRIGGERS: true

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_SSL_ENABLED: true
      ME_CONFIG_SITE_SSL_CRT_PATH: /etc/ssl/certs/todoapp.crt
      ME_CONFIG_SITE_SSL_KEY_PATH: /etc/ssl/private/todoapp.key
    volumes:
      - ./ssl/todoapp.crt:/etc/ssl/certs/todoapp.crt
      - ./ssl/todoapp.key:/etc/ssl/private/todoapp.key
    networks:
      - node-frontend-todoapp
      - node-backend-todoapp
    restart: always

  proxy:
    container_name: proxy
    image: nginx
    depends_on:
      - todoapp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/todoapp.crt:/etc/ssl/certs/todoapp.crt
      - ./ssl/todoapp.key:/etc/ssl/private/todoapp.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - node-frontend-todoapp
    restart: always

volumes:
  mongodata:
  appdata:

networks:
  node-frontend-todoapp:
  node-backend-todoapp:
    internal: true