version: "3.9"
services:
  node-socialmedia:
    image: socialmedia
    ports:
      - "3000:3000"
    networks:
      - node-frontend-socialmedia
      - node-backend-socialmedia
    volumes:
      - appdata:/var/www/html
    restart: always
    environment:
      - DATABASE_URL=mongodb://admin:admin@mongo:27017/socialmedia
      # - MONGODB_URL=mongodb://admin:admin@mongo:27017/socialmedia
      - MONGODB_URI=mongodb://mongo:27017/shopping
      - SECRET= NAAA
      - FB_CLIENT_ID= NAAA
      - FB_CLIENT_SECRET= NAAA
      - MONGO_DEFAULT_DATABASE=socialmedia
      - API_URL=http://localhost:3000

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - node-backend-socialmedia
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_ENABLE_ADMIN: true
      ME_CONFIG_SITE_ENABLE_DEBUGGER: true
      ME_CONFIG_SITE_ENABLE_TRIGGERS: true

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_SSL_ENABLED: true
      ME_CONFIG_SITE_SSL_CRT_PATH: /etc/ssl/certs/socialmedia.crt
      ME_CONFIG_SITE_SSL_KEY_PATH: /etc/ssl/private/socialmedia.key
    volumes:
      - ./ssl/socialmedia.crt:/etc/ssl/certs/socialmedia.crt
      - ./ssl/socialmedia.key:/etc/ssl/private/socialmedia.key
    networks:
      - node-frontend-socialmedia
      - node-backend-socialmedia
    restart: always

  proxy:
    container_name: proxy
    image: nginx
    depends_on:
      - node-socialmedia
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/socialmedia.crt:/etc/ssl/certs/socialmedia.crt
      - ./ssl/socialmedia.key:/etc/ssl/private/socialmedia.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - node-frontend-socialmedia
    restart: always

volumes:
  mongodata:
  appdata:

networks:
  node-frontend-socialmedia:
  node-backend-socialmedia:
    internal: true